# Generated by Django 6.0.2 on 2026-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_city',
            new_name='delivery_city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_country',
            new_name='delivery_country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_postal_code',
            new_name='delivery_postal_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_state',
            new_name='delivery_state',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash_on_delivery', 'Cash on Delivery')], default='bank_transfer', max_length=20),
        ),
    ]
